---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[cybera_grafana::default]
    attributes: {
      influxdb: {
        ipaddress: 10.0.0.1,
        influxdb: {
          config: {
            api: {
              port: 8086
            }
          }
        }
      }
    }
